[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Omit all environment variables that are being flagged as secrets
  SECRETS_SCAN_OMIT_KEYS = "PORTFOLIO_URL,NEXT_PUBLIC_SITE_NAME,NEXT_PUBLIC_SITE_URL,EMAIL_USER,EMAIL_PASS,EMAIL_HOST,EMAIL_PORT,EMAIL_TO"
  
  # Or temporarily disable secrets scanning while debugging
  # SECRETS_SCAN_ENABLED = false

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"